import Navbar from "@/components/Navbar";
import { Toaster } from "@/components/ui/sonner";
import ModalProvider from "@/providers/ModalProvider";
import SupabaseProvider from "@/providers/SupabaseProvider";
import ToasterProvider from "@/providers/ToasterProvider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

import localFont from "next/font/local";

const hellix = localFont({
  src: [
    {
      path: "./fonts/HellixTRIAL-Light.woff2",
      weight: "300",
    },
    {
      path: "./fonts/HellixTRIAL-Regular.woff2",
      weight: "400",
    },
    {
      path: "./fonts/HellixTRIAL-Bold.woff2",
      weight: "700",
    },
  ],
  variable: "--font-clean",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  viewport: "width=device-width, initial-scale=1.0, viewport-fit=cover",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className="scroll-smooth" lang="en">
      <body className={`${hellix.variable} font-clean`}>
        <div className="h-[10vh] z-[201] fixed w-full bg-offblack"></div>
        <ToasterProvider />
        <SupabaseProvider>
          {/* <UserProvider> */}
          <ModalProvider />
          <Navbar />
          {children}
          <Toaster />
          {/* <Footer /> */}
          {/* </UserProvider> */}
        </SupabaseProvider>
      </body>
    </html>
  );
}
