"use client";
import { checkoutOrder } from "@/lib/actions/course.actions";
import { CourseTypes } from "@/types";
import { loadStripe } from "@stripe/stripe-js";
import { useEffect } from "react";

// Make sure to call `loadStripe` outside of a component’s render to avoid
// recreating the `Stripe` object on every render.
loadStripe(process.env.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY!);

interface BuyButtonProps {
  listing: CourseTypes;
  session: any;
  disabled: any;
}

const BuyButton = ({ listing, session, disabled }: BuyButtonProps) => {
  useEffect(() => {
    // Check to see if this is a redirect back from Checkout
    const query = new URLSearchParams(window.location.search);
    if (query.get("success")) {
      console.log("Order placed! You will receive an email confirmation.");
    }

    if (query.get("canceled")) {
      console.log(
        "Order canceled -- continue to shop around and checkout when you’re ready."
      );
    }
  }, []);

  const userId = session?.user?.id;
  const eventFinished = new Date(listing.date.from) < new Date();
  console.log(disabled, "iscoursecreator");
  const onCheckout = async (e: any) => {
    const order = {
      title: listing.title,
      listingId: listing.id,
      price: listing.price,
      buyer: userId,
    };

    await checkoutOrder(order);
  };
  return (
    <form action={onCheckout}>
      <button
        disabled={eventFinished || disabled !== undefined}
        className={` ${
          eventFinished && "cursor-not-allowed bg-zinc-300"
        } border-[1px] mt-2 font-bold w-fit py-2 px-6 rounded-[2px] border-black solid`}
      >
        {eventFinished ? "Event has finished" : "Buy Ticket"}
      </button>
    </form>
  );
};

export default BuyButton;

/*
{
  id: 70,
  created_at: '2024-08-07T15:06:01.911293+00:00',
  title: 'currentEventcurrentEvent',
  description: 'currentEvent',
  imageSrc: '[{"uid":"rc-upload-1723043044295-3","lastModified":1538510052921,"lastModifiedDate":"2018-10-02T19:54:12.921Z","name":"11781896_1646234975624071_1469956913638563508_n.jpg","size":66172,"type":"image/jpeg","percent":100,"originFileObj":{"uid":"rc-upload-1723043044295-3"},"status":"done","response":"<!DOCTYPE html><html lang=\\"en\\"><head><meta charSet=\\"utf-8\\"/><meta name=\\"viewport\\" content=\\"width=device-width, initial-scale=1\\"/><link rel=\\"stylesheet\\" href=\\"/_next/static/css/app/layout.css?v=1723043125083\\" data-precedence=\\"next_static/css/app/layout.css\\"/><link rel=\\"preload\\" as=\\"script\\" fetchPriority=\\"low\\" href=\\"/_next/static/chunks/webpack.js?v=1723043125083\\"/><script src=\\"/_next/static/chunks/main-app.js?v=1723043125083\\" async=\\"\\"></script><script src=\\"/_next/static/chunks/app-pages-internals.js\\" async=\\"\\"></script><script src=\\"/_next/static/chunks/app/layout.js\\" async=\\"\\"></script><script src=\\"/_next/static/chunks/app/courses/page.js\\" async=\\"\\"></script><title>Create Next App</title><meta name=\\"description\\" content=\\"Generated by create next app\\"/><link rel=\\"icon\\" href=\\"/favicon.ico\\" type=\\"image/x-icon\\" sizes=\\"16x16\\"/><script src=\\"/_next/static/chunks/polyfills.js\\" noModule=\\"\\"></script></head><body class=\\"__variable_791122 font-clean\\"><div class=\\"h-[10vh] z-[200] fixed w-full bg-offblack\\"></div><div style=\\"position:fixed;z-index:9999;top:16px;left:16px;right:16px;bottom:16px;pointer-events:none\\"></div><nav class=\\"flex justify-between z-[3000] text-black fixed w-screen h-[10vh] \\"><h1 class=\\"mix-blend-difference text-white justify-self-start self-center z-50 p-6 text-3xl font-bold\\"><a class=\\"mix-blend-difference \\" href=\\"/\\">courseapp</a></h1><div class=\\"flex items-center\\"><h1 class=\\"hidden md:flex p-6 text-xl align-baseline text-white font-bold  gap-4\\"><span class=\\"cursor-pointer\\">Create a listing</span></h1><div class=\\"hidden text-nowrap items-center md:flex p-6 text-xl align-baseline text-white font-bold  gap-4\\"><a href=\\"/profile\\">My Profile</a><button class=\\"inline-flex items-center justify-center whitespace-nowrap ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 border w-full text-black border-input bg-background hover:bg-offblack hover:text-accent-foreground h-10 px-4 py-2 font-bold text-lg\\">Log Out</button></div><div class=\\"md:hidden fixed left-0 top-0\\"><div class=\\"hamburger_container__EXagG right-0 absolute z-[1001] false\\"><svg xmlns=\\"http://www.w3.org/2000/svg\\" width=\\"80\\" height=\\"80\\" viewBox=\\"0 0 200 200\\"><g stroke-width=\\"6.5\\" stroke-linecap=\\"round\\"><path d=\\"M72 82.286h28.75\\" fill=\\"#009100\\" fill-rule=\\"evenodd\\" stroke=\\"white\\"></path><path d=\\"M100.75 103.714l72.482-.143c.043 39.398-32.284 71.434-72.16 71.434-39.878 0-72.204-32.036-72.204-71.554\\" fill=\\"none\\" stroke=\\"white\\"></path><path d=\\"M72 125.143h28.75\\" fill=\\"#009100\\" fill-rule=\\"evenodd\\" stroke=\\"white\\"></path><path d=\\"M100.75 103.714l-71.908-.143c.026-39.638 32.352-71.674 72.23-71.674 39.876 0 72.203 32.036 72.203 71.554\\" fill=\\"none\\" stroke=\\"white\\"></path><path d=\\"M100.75 82.286h28.75\\" fill=\\"#009100\\" fill-rule=\\"evenodd\\" stroke=\\"white\\"></path><path d=\\"M100.75 125.143h28.75\\" fill=\\"#009100\\" fill-rule=\\"evenodd\\" stroke=\\"white\\"></path></g></svg></div></div></div></nav><section class=\\"\\"><div class=\\"h-[10vh] z-[100] fixed w-full bg-black\\"></div><section class=\\"bg-white w-full flex flex-col   h-fit pt-[12vh]\\"><div class=\\"absolute z-50 row-span-2 w-full px-2 col-span-full\\"><div class=\\"cursor-pointer hover:bg-primary/90 bg-offblack overflow-hidden h-[20%] text-primary-foreground  p-3 flex gap-3 items-center\\" style=\\"height:6vh\\"><svg xmlns=\\"http://www.w3.org/2000/svg\\" width=\\"24\\" height=\\"24\\" viewBox=\\"0 0 24 24\\" fill=\\"none\\" stroke=\\"currentColor\\" stroke-width=\\"2\\" stroke-linecap=\\"round\\" stroke-linejoin=\\"round\\" class=\\"lucide lucide-search\\"><circle cx=\\"11\\" cy=\\"11\\" r=\\"8\\"></circle><path d=\\"m21 21-4.3-4.3\\"></path></svg><h2 class=\\"inline-block w-full\\">Any Category - Any City</h2><div class=\\"md:flex w-full h-full  gap-5 items-center\\" style=\\"opacity:0;visibility:collapse;will-change:transform,opacity;transform:translateY(30%)\\"><svg xmlns=\\"http://www.w3.org/2000/svg\\" width=\\"24\\" height=\\"24\\" viewBox=\\"0 0 24 24\\" fill=\\"none\\" stroke=\\"currentColor\\" stroke-width=\\"2\\" stroke-linecap=\\"round\\" stroke-linejoin=\\"round\\" class=\\"lucide lucide-x absolute top-0 right-0 cursor-pointer\\" scale=\\"2\\"><path d=\\"M18 6 6 18\\"></path><path d=\\"m6 6 12 12\\"></path></svg><div class=\\"md:w-1/4 mb-4 md:mb-0 self-end\\"><h2 class=\\"font-bold mb-2\\">Choose a Category:</h2><button class=\\"inline-flex items-center whitespace-nowrap text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 border text-black border-input bg-background hover:bg-offblack hover:text-accent-foreground h-10 px-3 py-2 w-full justify-start\\" type=\\"button\\" aria-haspopup=\\"dialog\\" aria-expanded=\\"false\\" aria-controls=\\"radix-:R15eb9uufcq:\\" data-state=\\"closed\\">+ Choose a category</button></div><div class=\\"self-end  md:w-1/4\\"><h2 class=\\"font-bold mb-2\\">Search for a city:</h2><div class=\\" autocomplete-container\\"><input class=\\"flex h-10 w-full rounded-[2px] border border-input bg-background px-3 py-2 text-sm ring-offset-background file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50 text-offblack\\"/></div></div><button class=\\"inline-flex items-center justify-center whitespace-nowrap text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 bg-accent text-white hover:bg-secondary/80 h-10 px-4 py-2 self-end mt-4 md:mt-0\\">Apply Filters</button></div></div><hr class=\\"w-full\\"/></div><section class=\\"pt-16 px-2\\"><div class=\\"w-full\\"><div class=\\"flex flex-col items-center gap-10\\"><ul class=\\"grid w-full grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 md:gap-8 xl:gap-10\\"><li class=\\"flex justify-center\\"><div class=\\"grid-rows-1 w-full grid grid-cols-1 justify-center mt-2 \\"><div class=\\"   bg-slate-200   aspect-video   row-span-3   relative   \\"><a href=\\"/courses/69\\"><img alt=\\"Hmburg\\" loading=\\"lazy\\" decoding=\\"async\\" data-nimg=\\"fill\\" style=\\"position:absolute;height:100%;width:100%;left:0;top:0;right:0;bottom:0;object-fit:cover;color:transparent\\" sizes=\\"100vw\\" srcSet=\\"/_next/image?url=https%3A%2F%2Fdliobleuxirzpstdyzcn.supabase.co%2Fstorage%2Fv1%2Fobject%2Fpublic%2Fimages%2Frc-upload-1723041149976-3&amp;w=640&amp;q=75 640w, /_next/image?url=https%3A%2F%2Fdliobleuxirzpstdyzcn.supabase.co%2Fstorage%2Fv1%2Fobject%2Fpublic%2Fimages%2Frc-upload-1723041149976-3&amp;w=750&amp;q=75 750w, /_next/image?url=https%3A%2F%2Fdliobleuxirzpstdyzcn.supabase.co%2Fstorage%2Fv1%2Fobject%2Fpublic%2Fimages%2Frc-upload-1723041149976-3&amp;w=828&amp;q=75 828w, /_next/image?url=https%3A%2F%2Fdliobleuxirzpstdyzcn.supabase.co%2Fstorage%2Fv1%2Fobject%2Fpublic%2Fimages%2Frc-upload-1723041149976-3&amp;w=1080&amp;q=75 1080w, /_next/image?url=https%3A%2F%2Fdliobleuxirzpstdyzcn.supabase.co%2Fstorage%2Fv1%2Fobject%2Fpublic%2Fimages%2Frc-upload-1723041149976-3&amp;w=1200&amp;q=75 1200w, /_next/image?url=https%3A%2F%2Fdliobleuxirzpstdyzcn.supabase.co%2Fstorage%2Fv1%2Fobject%2Fpublic%2Fimages%2Frc-upload-1723041149976-3&amp;w=1920&amp;q=75 1920w, /_next/image?url=https%3A%2F%2Fdliobleuxirzpstdyzcn.supabase.co%2Fstorage%2Fv1%2Fobject%2Fpublic%2Fimages%2Frc-upload-1723041149976-3&amp;w=2048&amp;q=75 2048w, /_next/image?url=https%3A%2F%2Fdliobleuxirzpstdyzcn.supabase.co%2Fstorage%2Fv1%2Fobject%2Fpublic%2Fimages%2Frc-upload-1723041149976-3&amp;w=3840&amp;q=75 3840w\\" src=\\"/_next/image?url=https%3A%2F%2Fdliobleuxirzpstdyzcn.supabase.co%2Fstorage%2Fv1%2Fobject%2Fpublic%2Fimages%2Frc-upload-1723041149976-3&amp;w=3840&amp;q=75\\"/></a><div class=\\"absolute right-2 top-2 flex flex-col gap-4 bg-white p-3 shadow-sm z-20   transition-all\\"><a href=\\"/courses/69/update\\"><svg stroke=\\"currentColor\\" fill=\\"currentColor\\" stroke-width=\\"0\\" viewBox=\\"0 0 1024 1024\\" class=\\"hover:scale-125\\" height=\\"1em\\" width=\\"1em\\" xmlns=\\"http://www.w3.org/2000/svg\\"><path d=\\"M880 836H144c-17.7 0-32 14.3-32 32v36c0 4.4 3.6 8 8 8h784c4.4 0 8-3.6 8-8v-36c0-17.7-14.3-32-32-32zm-622.3-84c2 0 4-.2 6-.5L431.9 722c2-.4 3.9-1.3 5.3-2.8l423.9-423.9a9.96 9.96 0 0 0 0-14.1L694.9 114.9c-1.9-1.9-4.4-2.9-7.1-2.9s-5.2 1-7.1 2.9L256.8 538.8c-1.5 1.5-2.4 3.3-2.8 5.3l-29.5 168.2a33.5 33.5 0 0 0 9.4 29.8c6.6 6.4 14.9 9.9 23.8 9.9z\\"></path></svg></a><button type=\\"button\\" aria-haspopup=\\"dialog\\" aria-expanded=\\"false\\" aria-controls=\\"radix-:R2id9uufcq:\\" data-state=\\"closed\\" class=\\"hover:scale-125 z-20 \\"><svg stroke=\\"currentColor\\" fill=\\"currentColor\\" stroke-width=\\"0\\" viewBox=\\"0 0 1024 1024\\" height=\\"1em\\" width=\\"1em\\" xmlns=\\"http://www.w3.org/2000/svg\\"><path d=\\"M864 256H736v-80c0-35.3-28.7-64-64-64H352c-35.3 0-64 28.7-64 64v80H160c-17.7 0-32 14.3-32 32v32c0 4.4 3.6 8 8 8h60.4l24.7 523c1.6 34.1 29.8 61 63.9 61h454c34.2 0 62.3-26.8 63.9-61l24.7-523H888c4.4 0 8-3.6 8-8v-32c0-17.7-14.3-32-32-32zm-200 0H360v-72h304v72z\\"></path></svg></button></div><div class=\\"bg-offblack absolute bottom-2 right-2 py-2 px-5\\"><h3 class=\\"text-white font-bold\\">9000kr</h3></div></div><div class=\\"flex flex-col mt-2\\"><div class=\\"flex text-nowrap  text-sm justify-between text-zinc-500\\"><h2>August 14, 2024</h2><h2>Hosted by<!-- --> <p class=\\"text-offblack font-bold inline-block\\">You<'... 49012 more characters,
  user: 'f9b8313a-99cf-4a7f-95c1-18ef313f38ee',
  category: 'Parenting and Family',
  date: { from: '2024-08-07T22:00:00.000Z', to: '2024-08-08T22:00:00.000Z' },
  location: '{"formatted_address":"70 Stuttgart, Tyskland","geometry":{"location":{"lat":48.7758459,"lng":9.1829321},"viewport":{"south":48.69201873737177,"west":9.03860531551151,"north":48.8663994401746,"east":9.315825130826587}},"name":"Stuttgart","html_attributions":[]}',
  capacity: 255,
  price: 500,
  image: null
} {
  user: {
    id: 'f9b8313a-99cf-4a7f-95c1-18ef313f38ee',
    aud: 'authenticated',
    role: 'authenticated',
    email: 'hajibtarik@gmail.com',
    email_confirmed_at: '2023-10-22T19:26:07.710048Z',
    phone: '',
    confirmation_sent_at: '2023-10-22T19:25:56.347404Z',
    confirmed_at: '2023-10-22T19:26:07.710048Z',
    recovery_sent_at: '2024-08-02T14:43:25.682599Z',
    last_sign_in_at: '2024-08-06T00:36:04.469172Z',
    app_metadata: { provider: 'email', providers: [Array] },
    user_metadata: {},
    identities: [ [Object] ],
    created_at: '2023-10-22T19:25:56.334947Z',
    updated_at: '2024-08-07T15:33:22.162001Z',
    is_anonymous: false
  }
}*/
